version: '3.1'

services:
  db:
    image: mysql
    container_name: mysqldcb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldcb
    expose:
      - '3306'
    ports:
      - '3306:3306'